backend:
  name: git-gateway
  branch: main
media_folder: site/static/img
public_folder: img
collections:
  - name: post
    label: Post
    folder: site/content/post
    path: '{{slug}}/index'
    create: true
    fields:
      - name: title
        widget: string
        label: Title
      - name: date
        widget: datetime
        label: Publish Date
      - name: title
        widget: text
        label: Intro Blurb
      - name: image
        widget: image
        label: Image
        required: false
      - name: body
        widget: markdown
        label: Body
      - name: hero_section
        widget: object
        label: Hero Section
        fields:
          - name: title
            widget: string
            label: Title
            required: false
            hint: The title of the section
          - name: subtitle
            widget: string
            label: Subtitle
            required: false
            hint: The subtitle of the section
          - name: actions
            widget: list
            label: Action Buttons
            required: false
            fields:
              - name: label
                widget: string
                label: Label
                required: true
              - name: url
                widget: string
                label: URL
                required: true
              - name: style
                widget: select
                label: Style
                required: true
                default: link
                options:
                  - link
                  - primary
                  - secondary
              - name: new_window
                widget: boolean
                label: Open in new tab/window
                required: false
                default: false
              - name: type
                widget: hidden
                label: Object Type
                required: true
                hint: The type of the object
                default: action
          - name: align
            widget: select
            label: Align
            required: false
            default: left
            hint: The alignment of the text content
            options:
              - left
              - right
              - center
          - name: image
            widget: image
            label: Image
            required: false
            hint: The image of the section
          - name: image_position
            widget: select
            label: Image Position
            required: false
            default: left
            hint: The position of the image
            options:
              - left
              - right
          - name: has_background
            widget: boolean
            label: Enable section background
            required: false
            default: false
          - name: background
            widget: object
            label: Background Configuration
            required: false
            fields:
              - name: background_color
                widget: select
                label: Background Color
                required: false
                default: white
                hint: The background color of the section
                options:
                  - white
                  - gray
                  - blue
              - name: background_image
                widget: image
                label: Background Image
                required: false
                hint: The image displayed in the background of the section
              - name: background_image_opacity
                widget: number
                label: Background Image Opacity
                required: false
                hint: >-
                  An integer between 0 and 100. A lower value makes the image
                  more transparent.
                valueType: int
              - name: background_image_size
                widget: select
                label: Background Image Size
                required: false
                default: cover
                hint: The size of the background image
                options:
                  - auto
                  - contain
                  - cover
              - name: background_image_repeat
                widget: select
                label: Background Image Repeat
                required: false
                default: no-repeat
                hint: Repeat the image to cover the whole area.
                options:
                  - repeat
                  - no-repeat
          - name: type
            widget: hidden
            label: Object Type
            required: true
            hint: The type of the object
            default: hero_section
  - name: pages
    label: Pages
    files:
      - file: site/content/_index.md
        label: Home Page
        name: home
        fields:
          - label: Title
            name: title
            widget: string
          - label: Subtitle
            name: subtitle
            widget: string
          - label: Image
            name: image
            widget: image
          - label: Blurb
            name: blurb
            widget: object
            fields:
              - label: Heading
                name: heading
                widget: string
              - label: Text
                name: text
                widget: text
          - label: Intro
            name: intro
            widget: object
            fields:
              - label: Heading
                name: heading
                widget: string
              - label: Text
                name: text
                widget: text
          - label: Products
            name: products
            widget: list
            fields:
              - label: Image
                name: image
                widget: image
              - label: Text
                name: text
                widget: text
          - label: Values
            name: values
            widget: object
            fields:
              - label: Heading
                name: heading
                widget: string
              - label: Text
                name: text
                widget: text
      - file: site/content/contact/_index.md
        label: Contact Page
        name: contact
        fields:
          - label: Title
            name: title
            widget: string
          - label: Logo
            name: logo
            widget: image
          - label: Body
            name: body
            widget: markdown
          - label: Contact Entries
            name: contact_entries
            widget: list
            fields:
              - label: Heading
                name: heading
                widget: string
              - label: Text
                name: text
                widget: text
      - file: site/content/products/_index.md
        label: Products Page
        name: products
        fields:
          - label: Title
            name: title
            widget: string
          - label: Image
            name: image
            widget: image
          - label: Intro
            name: intro
            widget: object
            fields:
              - label: Heading
                name: heading
                widget: string
              - label: Description
                name: description
                widget: text
              - label: Blurbs
                name: blurbs
                widget: list
                fields:
                  - label: Image
                    name: image
                    widget: image
                  - label: Text
                    name: text
                    widget: text
          - label: Main
            name: main
            widget: object
            fields:
              - label: Heading
                name: heading
                widget: string
              - label: Description
                name: description
                widget: text
              - label: Image1
                name: image1
                widget: object
                fields:
                  - label: Image
                    name: image
                    widget: image
                  - label: Alt
                    name: alt
                    widget: string
              - label: Image2
                name: image2
                widget: object
                fields:
                  - label: Image
                    name: image
                    widget: image
                  - label: Alt
                    name: alt
                    widget: string
              - label: Image3
                name: image3
                widget: object
                fields:
                  - label: Image
                    name: image
                    widget: image
                  - label: Alt
                    name: alt
                    widget: string
          - label: Testimonials
            name: testimonials
            widget: list
            fields:
              - label: Quote
                name: quote
                widget: string
              - label: Author
                name: author
                widget: string
          - label: Full_image
            name: full_image
            widget: image
          - label: Pricing
            name: pricing
            widget: object
            fields:
              - label: Heading
                name: heading
                widget: string
              - label: Description
                name: description
                widget: string
              - label: Plans
                name: plans
                widget: list
                fields:
                  - label: Plan
                    name: plan
                    widget: string
                  - label: Price
                    name: price
                    widget: string
                  - label: Description
                    name: description
                    widget: string
                  - label: Items
                    name: items
                    widget: list
      - file: site/content/values/_index.md
        label: Values Page
        name: values
        fields:
          - label: Title
            name: title
            widget: string
          - label: Image
            name: image
            widget: image
          - label: Values
            name: values
            widget: list
            fields:
              - label: Heading
                name: heading
                widget: string
              - label: Text
                name: text
                widget: text
              - label: Image
                name: imageUrl
                widget: image
  - name: site_settings
    label: Site Settings
    files:
      - file: site/data/footer.json
        label: Footer
        name: footer
        fields:
          - label: Title
            name: title
            widget: string
          - label: Blurb
            name: blurb
            widget: text
      - file: site/hugo.toml
        label: Hugo Config
        name: config
        editor:
          preview: false
        fields:
          - label: Site Title for Browser Tab
            name: title
            widget: string
          - label: Params
            name: params
            widget: object
            fields:
              - label: Open Graph Image
                name: images
                widget: list
                field:
                  label: Image
                  name: image
                  widget: image
